# Generated by Django 3.1.1 on 2020-11-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[('เชิงบวก', 1), ('เชิงลบ', 0)], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_iit.choice_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Ascend',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iit.choice')),
                ('notting', models.FloatField(default=0.0, verbose_name='น้อยที่สุดหรือไม่มีเลย')),
                ('low', models.FloatField(default=0.0, verbose_name='น้อย')),
                ('very', models.FloatField(default=0.0, verbose_name='มาก')),
                ('many', models.FloatField(default=0.0, verbose_name='มากที่สุด')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('iit.choice',),
        ),
        migrations.CreateModel(
            name='Exist',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iit.choice')),
                ('have', models.FloatField(default=0.0, verbose_name='มี')),
                ('notting', models.FloatField(default=0.0, verbose_name='ไม่มี')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('iit.choice',),
        ),
    ]
