# Generated by Django 3.1.1 on 2020-11-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเด็นการประเมิน',
                'verbose_name_plural': 'ประเด็นการประเมิน',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.BooleanField(choices=[(True, 'มีข้อย่อย'), (False, 'ไม่มีข้อย่อย')], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.assessmentissues')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ascend',
            options={'verbose_name': 'ตัวเลือกแบบ น้อยที่สุด-มากที่สุด', 'verbose_name_plural': 'ตัวเลือกแบบ น้อยที่สุด-มากที่สุด'},
        ),
        migrations.AlterModelOptions(
            name='exist',
            options={'verbose_name': 'ตัวเลือกแบบ มี/ไม่มี', 'verbose_name_plural': 'ตัวเลือกแบบ มี/ไม่มี'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='type',
            field=models.IntegerField(choices=[(1, 'เชิงบวก'), (0, 'เชิงลบ')]),
        ),
        migrations.CreateModel(
            name='IssueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.choice')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.issue')),
            ],
        ),
    ]
