# Generated by Django 3.1.1 on 2020-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iit', '0002_auto_20201122_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'หัวข้อการประเมิน', 'verbose_name_plural': 'หัวข้อการประเมิน'},
        ),
        migrations.AlterModelOptions(
            name='issuedetail',
            options={'verbose_name': 'หัวข้อ', 'verbose_name_plural': 'หัวข้อ'},
        ),
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
