# Generated by Django 3.1.1 on 2020-11-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iit', '0003_auto_20201122_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iit.choice')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำตอบ')),
            ],
            options={
                'verbose_name': 'ตัวเลือกแบบ แบบคำตอบ',
                'verbose_name_plural': 'ตัวเลือกแบบ แบบคำตอบ',
            },
            bases=('iit.choice',),
        ),
        migrations.AlterField(
            model_name='assessmentissues',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
