# Generated by Django 3.1.1 on 2020-11-22 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0013_auto_20201122_0833'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iit', '0006_auto_20201122_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0, verbose_name='คะแนน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('assessmentIssues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.assessmentissues')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.issue')),
                ('issueDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.issuedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.year')),
            ],
            options={
                'verbose_name': 'การตอบแบบประเมิน',
                'verbose_name_plural': 'การตอบแบบประเมิน',
            },
        ),
    ]
