# Generated by Django 3.1.1 on 2020-11-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0013_auto_20201122_0833'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iit', '0007_answerissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iit.year')),
            ],
            options={
                'verbose_name': 'การตอบข้อเสนอแนะ',
                'verbose_name_plural': 'การตอบข้อเสนอแนะ',
            },
        ),
    ]
