# Generated by Django 3.1.1 on 2020-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iit', '0010_auto_20201129_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerissue',
            options={'verbose_name': 'การตอบแบบประเมิน (ข้อมูลดิบ)', 'verbose_name_plural': 'การตอบแบบประเมิน (ข้อมูลดิบ)'},
        ),
        migrations.AlterModelOptions(
            name='answersuggestion',
            options={'verbose_name': 'การตอบข้อเสนอแนะ ', 'verbose_name_plural': 'การตอบข้อเสนอแนะ '},
        ),
        migrations.AlterModelOptions(
            name='userinanswer',
            options={'verbose_name': 'การตอบแบบประเมิน (รายบุคลล)', 'verbose_name_plural': 'การตอบแบบประเมิน (รายบุคลล)'},
        ),
        migrations.AddField(
            model_name='year',
            name='people',
            field=models.IntegerField(default=0, verbose_name='เปิดรับการประเมิน (คน)'),
        ),
    ]
