# Generated by Django 3.1.1 on 2022-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iit', '0012_remove_year_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.TextField(),
        ),
    ]
