# Generated by Django 3.1.1 on 2021-03-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ita', '0024_auto_20210322_0319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateOIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(choices=[(0, 0), (0.5, 0.5), (1, 1)], default=0.0, null=True, verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.agency', verbose_name='หน่วยงานที่ส่ง')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.rate', verbose_name='หัวข้อการตรวจสอบ')),
                ('rate_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.ratestatus', verbose_name='สถานะการตรวจสอบ')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='หน่วยงานที่ตรวจสอบ')),
            ],
        ),
    ]
