# Generated by Django 3.1.1 on 2021-02-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ita', '0020_reportagencyeit_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='ปีงบประมาณ')),
                ('iit', models.FloatField(default=0.0)),
                ('eit', models.FloatField(default=0.0)),
                ('oit', models.FloatField(default=0.0)),
                ('all', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency', verbose_name='หน่วยงาน/คณะ')),
            ],
            options={
                'verbose_name': 'รายงานคะแนนรวม',
                'verbose_name_plural': 'รายงานคะแนนรวม',
            },
        ),
    ]
