# Generated by Django 3.1.1 on 2021-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportdetail_reportraweit_reportrawiit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportall',
            name='rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ระดับ'),
        ),
        migrations.AlterField(
            model_name='reportdetail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อ'),
        ),
    ]
