# Generated by Django 3.1.1 on 2021-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210206_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportraweit',
            name='raw',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportrawiit',
            name='raw',
            field=models.TextField(),
        ),
    ]
