# Generated by Django 3.1.1 on 2021-03-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='เวอร์ชัน')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่าการเข้าถึงเว็บไซต์ (Client)',
                'verbose_name_plural': 'ตั้งค่าการเข้าถึงเว็บไซต์ (Client)',
            },
        ),
    ]
