# Generated by Django 3.1.1 on 2020-11-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเด็นการประเมิน',
                'verbose_name_plural': 'ประเด็นการประเมิน',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'เชิงบวก'), (0, 'เชิงลบ'), (3, 'ทั่วไป')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_eit.choice_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.BooleanField(choices=[(True, 'มีข้อย่อย'), (False, 'ไม่มีข้อย่อย')], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.assessmentissues')),
            ],
            options={
                'verbose_name': 'หัวข้อการประเมิน',
                'verbose_name_plural': 'หัวข้อการประเมิน',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False, verbose_name='ปิดการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ปีงบประมาณ',
                'verbose_name_plural': 'ปีงบประมาณ',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eit.choice')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำตอบ')),
            ],
            options={
                'verbose_name': 'ตัวเลือกแบบ แบบคำตอบ',
                'verbose_name_plural': 'ตัวเลือกแบบ แบบคำตอบ',
            },
            bases=('eit.choice',),
        ),
        migrations.CreateModel(
            name='Ascend',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eit.choice')),
                ('notting', models.FloatField(default=0.0, verbose_name='น้อยที่สุดหรือไม่มีเลย')),
                ('low', models.FloatField(default=0.0, verbose_name='น้อย')),
                ('very', models.FloatField(default=0.0, verbose_name='มาก')),
                ('many', models.FloatField(default=0.0, verbose_name='มากที่สุด')),
            ],
            options={
                'verbose_name': 'ตัวเลือกแบบ น้อยที่สุด-มากที่สุด',
                'verbose_name_plural': 'ตัวเลือกแบบ น้อยที่สุด-มากที่สุด',
            },
            bases=('eit.choice',),
        ),
        migrations.CreateModel(
            name='Exist',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eit.choice')),
                ('have', models.FloatField(default=0.0, verbose_name='มี')),
                ('notting', models.FloatField(default=0.0, verbose_name='ไม่มี')),
            ],
            options={
                'verbose_name': 'ตัวเลือกแบบ มี/ไม่มี',
                'verbose_name_plural': 'ตัวเลือกแบบ มี/ไม่มี',
            },
            bases=('eit.choice',),
        ),
        migrations.CreateModel(
            name='IssueDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.choice')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.issue')),
            ],
            options={
                'verbose_name': 'หัวข้อ',
                'verbose_name_plural': 'หัวข้อ',
            },
        ),
        migrations.AddField(
            model_name='assessmentissues',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eit.year', verbose_name='ปีงบประมาณ'),
        ),
    ]
