# Generated by Django 3.1.1 on 2020-11-22 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ita', '0013_auto_20201122_0833'),
        ('eit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSuggestionEit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.year')),
            ],
            options={
                'verbose_name': 'การตอบข้อเสนอแนะ',
                'verbose_name_plural': 'การตอบข้อเสนอแนะ',
            },
        ),
        migrations.CreateModel(
            name='AnswerIssueEit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0, verbose_name='คะแนน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('assessmentIssues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.assessmentissues')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.issue')),
                ('issueDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.issuedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.year')),
            ],
            options={
                'verbose_name': 'การตอบแบบประเมิน',
                'verbose_name_plural': 'การตอบแบบประเมิน',
            },
        ),
    ]
