# Generated by Django 3.1.1 on 2020-11-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eit', '0002_answerissueeit_answersuggestioneit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerissueeit',
            name='value_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answerissueeit',
            name='value_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eit.choice'),
        ),
        migrations.AlterField(
            model_name='answerissueeit',
            name='value',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='คะแนน'),
        ),
    ]
