# Generated by Django 3.1.1 on 2023-01-09 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eit', '0004_auto_20220120_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerissueeit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อผู้ประเมิน'),
        ),
        migrations.AddField(
            model_name='answerissueeit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์โทรผู้ประะเมิน'),
        ),
        migrations.AlterField(
            model_name='answerissueeit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
