# Generated by Django 3.1.1 on 2024-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eit', '0006_auto_20230110_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascend',
            name='manyest',
            field=models.FloatField(default=0.0, verbose_name='มากที่สุดที่สุดหรือไม่มีเลย'),
        ),
        migrations.AddField(
            model_name='ascend',
            name='nottingest',
            field=models.FloatField(default=0.0, verbose_name='น้อยที่สุดหรือไม่มีเลย'),
        ),
        migrations.AlterField(
            model_name='ascend',
            name='many',
            field=models.FloatField(default=0.0, verbose_name='มากพอสมควร'),
        ),
        migrations.AlterField(
            model_name='ascend',
            name='notting',
            field=models.FloatField(default=0.0, verbose_name='น้อยมาก'),
        ),
    ]
