# Generated by Django 3.1.1 on 2022-08-20 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ita', '0029_auto_20220821_0225'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='คุณธรรมเป้าหมาย')),
                ('problem', models.CharField(blank=True, max_length=250, null=True, verbose_name='ปัญหาที่อยากแก้')),
                ('good_fix', models.CharField(blank=True, max_length=250, null=True, verbose_name='กิจกรรม')),
                ('doing', models.CharField(blank=True, max_length=250, null=True, verbose_name='หน่วงาน')),
                ('kpi', models.CharField(blank=True, max_length=250, null=True, verbose_name='ตัวชี้วัด')),
                ('doing_date', models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปี ที่ดำเนินงาน')),
                ('money', models.FloatField(blank=True, default=0, null=True, verbose_name='งบประมาณในการดำเนินงาน')),
                ('responsible_user', models.CharField(blank=True, max_length=250, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agency', verbose_name='หน่วงาน')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Main_exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_user', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('tel', models.CharField(blank=True, max_length=250, null=True)),
                ('level', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignPassingExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moral_organization.main_exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SignAdminExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('work', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moral_organization.main_exercise')),
            ],
        ),
        migrations.AddField(
            model_name='main_exercise',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.year'),
        ),
        migrations.CreateModel(
            name='FinishPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='กิจกรรม/โครงการ')),
                ('doing_date', models.DateTimeField(blank=True, null=True, verbose_name='วัน เวลา ที่ดำเนินการ')),
                ('place', models.CharField(blank=True, max_length=250, null=True, verbose_name='สถานที่ ที่ดำเนินการ')),
                ('count_person', models.IntegerField(blank=True, default=0, null=True, verbose_name='จำนวนผู้เช้าร่วมกิจกรรม/โครงการ')),
                ('money', models.FloatField(blank=True, default=0, null=True, verbose_name='งบประมาณที่ใช้ในการดำเนินงาน')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดกิจกรรม/โครงการ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moral_organization.baseplan')),
                ('file', models.ManyToManyField(to='moral_organization.PlanFile', verbose_name='ไฟล์')),
            ],
        ),
        migrations.CreateModel(
            name='Do_exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.assessment')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.choice')),
                ('main_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.main_exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.year')),
            ],
        ),
        migrations.AddField(
            model_name='baseplan',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.year'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.category'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moral_organization.year'),
        ),
    ]
