# Generated by Django 3.1.1 on 2022-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moral_organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseplan',
            name='fix_want',
            field=models.TextField(blank=True, null=True, verbose_name='สิ่งที่อยากทำ'),
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='doing',
            field=models.TextField(blank=True, null=True, verbose_name='หน่วงาน'),
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='good_fix',
            field=models.TextField(blank=True, null=True, verbose_name='กิจกรรม'),
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='kpi',
            field=models.TextField(blank=True, null=True, verbose_name='ตัวชี้วัด'),
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='problem',
            field=models.TextField(blank=True, null=True, verbose_name='ปัญหาที่อยากแก้'),
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='responsible_user',
            field=models.TextField(blank=True, null=True, verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
