# Generated by Django 3.1.1 on 2022-10-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moral_organization', '0002_auto_20221020_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseplan',
            name='doing',
        ),
        migrations.AlterField(
            model_name='baseplan',
            name='fix_want',
            field=models.TextField(blank=True, null=True, verbose_name='ความดีที่อยากทำ'),
        ),
    ]
