# Generated by Django 3.1.2 on 2020-10-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเภทหน่วยงาน',
                'verbose_name_plural': 'ประเภทหน่วยงาน',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.agencytype')),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'หน่วยงาน',
            },
        ),
    ]
