# Generated by Django 3.1.2 on 2020-10-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='ข้อ')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเด็นการตรวจสอบ',
                'verbose_name_plural': 'ประเด็นการตรวจสอบ',
            },
        ),
        migrations.CreateModel(
            name='RateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สถานะการตรวจสอบ',
                'verbose_name_plural': 'สถานะการตรวจสอบ',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ปีการศึกษา',
                'verbose_name_plural': 'ปีการศึกษา',
            },
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='agencytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.agency')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.rate')),
                ('rate_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.ratestatus')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การตรวจสอบ',
                'verbose_name_plural': 'การตรวจสอบ',
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.year'),
        ),
    ]
