# Generated by Django 3.1.2 on 2020-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateresult',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
