# Generated by Django 3.1.2 on 2020-10-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0004_rateresult_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateresult',
            name='register_type',
            field=models.CharField(blank=True, choices=[('เสร็จสิ้น', 'เสร็จสิ้น'), ('อยู่ระหว่างการปรับปรุง', 'อยู่ระหว่างการปรับปรุง'), ('ไม่มีข้อมูล', 'ไม่มีข้อมูล')], max_length=255, null=True),
        ),
    ]
