# Generated by Django 3.1.1 on 2020-11-09 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ita', '0006_rateresult_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='status',
            field=models.BooleanField(default=False, verbose_name='ปิดการใช้งาน'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='register_type',
            field=models.CharField(choices=[('microsoft.com', 'microsoft.com'), ('google.com', 'google.com'), ('facebook.com', 'facebook.com'), ('ปกติ', 'ปกติ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rate',
            name='detail',
            field=models.TextField(verbose_name='รายระเอียด'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='หัวข้อ'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.year', verbose_name='ปีการศึกษา'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.agency', verbose_name='หน่วยงานที่ส่ง'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='ความคิดเห็น'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='passing',
            field=models.BooleanField(default=False, verbose_name='การอนุญาตจากหัวหน้าหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.rate', verbose_name='หัวข้อการตรวจสอบ'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='rate_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.ratestatus', verbose_name='สถานะการตรวจสอบ'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='register_type',
            field=models.CharField(blank=True, choices=[('เสร็จสิ้น', 'เสร็จสิ้น'), ('อยู่ระหว่างการปรับปรุง', 'อยู่ระหว่างการปรับปรุง'), ('ไม่มีข้อมูล', 'ไม่มีข้อมูล')], max_length=255, null=True, verbose_name='สถานะการส่ง'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='score',
            field=models.FloatField(default=0.0, null=True, verbose_name='คะแนน'),
        ),
        migrations.AlterField(
            model_name='rateresult',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tester', to=settings.AUTH_USER_MODEL, verbose_name='หน่วยงานที่ตรวจสอบ'),
        ),
    ]
