# Generated by Django 3.1.1 on 2020-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0007_auto_20201109_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False, verbose_name='ปิดการใช้งาน'),
        ),
    ]
