# Generated by Django 3.1.1 on 2020-11-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0010_rateresult_user_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passing',
            field=models.BooleanField(default=False, verbose_name='หัวหน้าหน่วยงาน'),
        ),
    ]
