# Generated by Django 3.1.1 on 2020-11-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0011_profile_passing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_up',
            field=models.BooleanField(default=False, verbose_name='บุลคากรภายใน'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='เปิดการใช้งาน'),
        ),
    ]
