# Generated by Django 3.1.1 on 2020-11-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0012_auto_20201110_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'ปีงบประมาณ', 'verbose_name_plural': 'ปีงบประมาณ'},
        ),
    ]
