# Generated by Django 3.1.1 on 2020-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0013_auto_20201122_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='count',
            field=models.IntegerField(default=0, verbose_name='จำนวนบุคลากร'),
        ),
        migrations.AddField(
            model_name='agency',
            name='eit',
            field=models.IntegerField(default=0, verbose_name='ค่าเป้าหมายกลุ่มตัวอย่างภายใน (EIT)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='iit',
            field=models.IntegerField(default=0, verbose_name='ค่าเป้าหมายกลุ่มตัวอย่างภายนอก (IIT)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='เกณฑ์กลุ่มตัวอย่าง(ร้อยละ)'),
        ),
    ]
