# Generated by Django 3.1.1 on 2020-12-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0014_auto_20201129_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oit',
            field=models.BooleanField(default=False, verbose_name='สามารถประเมิน OIT ได้'),
        ),
    ]
