# Generated by Django 3.1.1 on 2021-01-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0015_profile_oit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='หัวข้อ')),
                ('urls', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rateresult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.rateresult')),
            ],
            options={
                'verbose_name': 'url การตรวจสอบ',
                'verbose_name_plural': 'url การตรวจสอบ',
            },
        ),
    ]
