# Generated by Django 3.1.1 on 2021-01-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0017_profile_oit_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAgencyEit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ชื่อองค์กร/ชื่อ - นามสกุล *(ไม่ใส่คำนำหน้า)')),
                ('tel', models.TextField(blank=True, null=True, verbose_name='เบอร์')),
                ('email', models.TextField(blank=True, null=True, verbose_name='อีเมล์')),
                ('type', models.TextField(blank=True, null=True, verbose_name='ประเภทการติดต่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ita.agency', verbose_name='หน่วยงานที่ส่ง')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.year', verbose_name='ประจำปี')),
            ],
        ),
    ]
