# Generated by Django 3.1.1 on 2021-01-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eit', '0003_auto_20201125_0147'),
        ('ita', '0018_reportagencyeit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportagencyeit',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eit.year', verbose_name='ประจำปี'),
        ),
    ]
