# Generated by Django 3.1.1 on 2021-01-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0019_auto_20210124_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportagencyeit',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='ช่องทางการติดต่ออื่นๆ'),
        ),
    ]
