# Generated by Django 3.1.1 on 2021-02-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0021_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='ปิดการมองเห็น'),
        ),
    ]
