# Generated by Django 3.1.1 on 2021-02-10 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ita', '0022_agency_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='eit',
            field=models.IntegerField(default=0, verbose_name='ค่าเป้าหมายกลุ่มตัวอย่างภายนอก (EIT)'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='iit',
            field=models.IntegerField(default=0, verbose_name='ค่าเป้าหมายกลุ่มตัวอย่างภายใน (IIT)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='oit',
            field=models.BooleanField(default=False, verbose_name='แอดมินหน่วยงาน'),
        ),
        migrations.CreateModel(
            name='AgencyChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old', to='ita.agency', verbose_name='หน่วยงานเดิม')),
                ('agency_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='ita.agency', verbose_name='หน่วยงานที่เปลี่ยนแปลง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'การเปลี่ยนแปลงหน่วยงาน',
                'verbose_name_plural': 'การเปลี่ยนแปลงหน่วยงาน',
            },
        ),
    ]
