# Generated by Django 3.1.1 on 2021-03-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0023_auto_20210210_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ผู้ใช้ (รายระเอียดเชิงลึก)', 'verbose_name_plural': 'ผู้ใช้ (รายระเอียดเชิงลึก)'},
        ),
        migrations.AlterModelOptions(
            name='reportagencyeit',
            options={'verbose_name': 'ข้อมูลผู้มีส่วนได้ส่วนเสียภายนอก', 'verbose_name_plural': 'ข้อมูลผู้มีส่วนได้ส่วนเสียภายนอก'},
        ),
    ]
