# Generated by Django 3.1.1 on 2021-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0025_rate_type_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type_base',
            field=models.CharField(blank=True, choices=[('การเปิดเผยข้อมูล', 'การเปิดเผยข้อมูล'), ('การป้องกันการทุจริต', 'การป้องกันการทุจริต')], max_length=255, null=True, verbose_name='ประเภทตัวชี้วัด'),
        ),
    ]
