# Generated by Django 3.1.1 on 2021-09-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0026_auto_20210422_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='result_ppch',
            field=models.TextField(blank=True, null=True, verbose_name='ผลประเมินรายปี ปปช.'),
        ),
        migrations.AddField(
            model_name='year',
            name='status_ppch',
            field=models.BooleanField(default=False, verbose_name='แสดงผลประเมินรายปี ปปช.'),
        ),
    ]
