# Generated by Django 3.1.1 on 2021-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0027_auto_20210915_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับ'),
        ),
    ]
