# Generated by Django 3.1.1 on 2022-08-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0028_agency_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['number']},
        ),
    ]
